### ISSUE TITLE
hwo does queue work? how does bungeecord tech work? waterfall? needs testing

### ISSUE THREAD

**Issue by Lockless00** [LukasOfLockless/pidgeon-server-info#10]

**Comment by likethedrama** [comment]
bungeecord distributes the connections
queue could be a server with silly big limit, and there must be a plugin that is compatable with bungee. 
that plugin gotsta do this: assign line number to player. when a spot becomes open in main server, then allowa dude with the lowest queue number to connect

**Comment by likethedrama** [comment]
i can try make the plugin , but youll need to setup bungee
