### ISSUE TITLE
okay so /killquest what it does!?!?

### ISSUE THREAD

**Issue by likethedrama** [LukasOfLockless/pidgeon-server-info#12]
makes players kills count towards clearing the area. 
what if the player does /killquest in another area, new instance of object without the removal of the old object maybe? 
only remove objects from this array when players offline or when the area becomes cleared in Win()
also dont allow them fuckers to get added to the array if the area is cleared.

**Comment by Lockless00** [comment]
i like this

**Comment by Lockless00** [comment]
done
