### ISSUE TITLE
/logs

### ISSUE THREAD

**Issue by likethedrama** [LukasOfLockless/pidgeon-server-info#18]
need to let players know what is being logged and inspected. 
feels like an important thing for the players to know that we aint hacking their isp or anything

**Comment by likethedrama** [comment]
i mean what if we post code here and actually run acompletely different code. im just being pumpkin. atleast give players some hope of privacy

**Comment by Lockless00** [comment]
go ahead. ctrl alt G "FolderCreation()" should make it an easy search

**Comment by likethedrama** [comment]
yeh/privacy concerns satisfied. two buddies might go in dying tonight
