### ISSUE TITLE
ambience war

### ISSUE THREAD

**Issue by Lockless00** [LukasOfLockless/pidgeon-server-info#21]
its a sound playing module that ssurrounds a place, and plays sounds for players there.
created, checks for players to playt sound to, dies down after 5 minutes or smt. ticks every 15 ticks or smt. 
wish this plugins effect could be called from other plugins, like pvpExp and the raider thing

**Comment by likethedrama** [comment]
could these sounds be used to help indicate where the targets are during killquestraidpls moments?!. 
maybe
