### ISSUE TITLE
okay, so tests on raid

### ISSUE THREAD

**Issue by likethedrama** [LukasOfLockless/pidgeon-server-info#25]
1 /killquestraidpls needs to spawn monsters differently imho. maybe farther away  a bit. like 48 or 64 blocks from the call
2 them vexes are cool to fight. (died melee, ranged would be preferable) ravagers are intereting to fight too.
3. pillagers are easy to cheese with that gap method. what if there was 1/10 chance that pillager explodes like tnt
4. ravager steam blow could dig walls too
5. if killed when having no brain it could just makethe fight harder.  like maybe extra raid spawns or spawn vexes to harras the player, or smt as a negative reinforcement measure

**Comment by Lockless00** [comment]
i like 5, will change 1. 64 seems ok

**Comment by Lockless00** [comment]
idk about exploding tho. hope some extra creepers can help, like when nobrain kills occur
