### ISSUE TITLE
killquest plugin

### ISSUE THREAD

**Issue by Lockless00** [LukasOfLockless/pidgeon-server-info#6]
i had a friend on my minecraft server complain about creeper griefing
I'm the type of player who has really sweaty palms while playing . i know how to play block game and i try my best.
the friend is more on the casual side. likes building a little bit more than anything else. 
sooo.... after a little bit of thought i came up with a concept.
some Areas (smt like 1000blocks x 1000blocks each area) are able to track mob deaths. if enough monsters are killed, then the Area cancels any hostile mob event.
so my line of design goes like this : you want creepers to not grief your shit, you have grind for it. in this case the grind is 64 zombie kills, 64 skeleton kills, 64 creeper kills, 64 spider kills. a stack of each. the reward would be : an irreversable change in hostile spawning and one use of /lore or some shit. 
/lore would be a commad that allows to add a little bit of subtext on an item held in main hand.

**Comment by Lockless00** [comment]
cant trigger the spawnraidevent. feels stupid using the api

**Comment by likethedrama** [comment]
spider kills doentregister or dont show up on /killquest

**Comment by Lockless00** [comment]
i think done. clearing it also stops witches and endermen from spawning. so the only mob to farm from spawners remains the tinee tiny mineshaft spider.
could be considered a bug but idc atm
