### ISSUE TITLE
sleep 

### ISSUE THREAD

**Issue by Lockless00** [LukasOfLockless/pidgeon-server-info#7]
the code that i thought would make player sleep whenever doesnt work. it kicks the player out of bed on daybreak or generally throughout the sunny times. u know. not thunderstorm, not night.

**Comment by likethedrama** [comment]
stopping the daysleepget in getout is ok. itsthe vanilla server code that messes with thesleep during daytime andi dont think we need that. even tho it would be cool

**Comment by Lockless00** [comment]
https://hub.spigotmc.org/jira/browse/SPIGOT-6316?focusedCommentId=38567&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-38567

maybe can be done by sending sleep packets

**Comment by Lockless00** [comment]
how to send packets  hmmm
https://bukkit.org/threads/info-packets-nms-explained.177955/#:~:text=A%20packet%20is%20a%20bit,%2C%20teleports%2C%20stuff%20like%20that.
